name: gc_course_env
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
    - libigl
    - opencv-python
    - pyvista
  - gmsh
  - python=3.9
  - python-gmsh
  - matplotlib
  - jupyterlab
  - pytest
  - pytest-html
  - pytest-timeout
  - svgwrite
  - meshplot
  - triangle
